import { useEffect } from "react";
import { useRouter } from "next/router";
import { Heading } from "@chakra-ui/react";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import PageLayout from "Base/layout/PageLayout";
import CreateGame from "Game/features/CreateGame";

const Home = () => {
  const { t } = useTranslation("game");
  const router = useRouter();

  useEffect(() => {
    // Redirige automáticamente a /game/ cuando el componente se monta
    router.push("/game/");
  }, [router]);

  return (
    <>
      <Head>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <PageLayout>
        {{
          header: <Heading>{""}</Heading>,
          content: (
            <CreateGame navigateToCreateGame={() => router.push("/game/")} />
          ),
        }}
      </PageLayout>
      {/* Puedes descomentar esta sección para usar DataTable
      <Box as="main" p={4}>
        <DataTable columns={columns} data={[]} />
      </Box> */}
    </>
  );
};

export default Home;
